### ISSUE TITLE
nested interface properties are missing?

### ISSUE THREAD

**Issue by hugebdu** [Hookyns/ts-reflection#17]
Hola.
Are nested interfaces supported (see code below)?

```
interface Bar {
  age: number;
}

interface Foo {
  name: string;
  nested: Bar;
}

const typeOfFoo: Type = getType<Foo>();

typeOfFoo.getProperties()[1].type.getProperties() // is empty - expected???
```

thanks!

**Comment by Hookyns** [comment]
Hello @hugebdu,
this should work, there is no depth limit (I'll test it and reply), but we've already found similar problem and solved it, but it is not published yet. Hope I'll publish new version at the end of this week; it is huge set of changes, new options and generally much closer to the version 1.0.

**Comment by hugebdu** [comment]
@Hookyns thanks for your quick reply.
shall check the new version once published.

**Comment by hugebdu** [comment]
@Hookyns UPD:

if I define `nested` as optional (with `?`) I do get what I'd expect - see below:

```
interface Bar {
  age: number;
}

interface Foo {
  name: string;
  nested?: Bar;
}

const typeOfFoo: Type = getType<Foo>();

typeOfFoo.getProperties()[1].type.types[1].getProperties() // now I do have the properties as expected
```

hope that helps

**Comment by Hookyns** [comment]
I've made some tests and it is rly issue, even in new (not released yet) version.

> if I define nested as optional (with ?) I do get what I'd expect - see below:

That's interesting. 😆 
I'll look at it, thanks.

**Comment by hugebdu** [comment]
> if I define nested as optional (with ?) I do get what I'd expect - see below:

actually partially true.
it did happen with `ts-jest` in my project, but when I tried in your `examples/base-usage` it is still empty, regardless of `?`

and yes, I also tried the `devel` branch - same

**Comment by hugebdu** [comment]
I suspect some traversal issue in `getTypeCall`
didn't dig any deeper.

also adding `getType<Bar>()` call before `getType<Foo>()` resolves the issue

**Comment by Hookyns** [comment]
I've fixed the issue. There were some weird type reference.
After some tests I've found another issue,.. unrelated.. but

I'm preparing next version in `https://github.com/Hookyns/ts-reflection/tree/feature/refactored-stores` you can test it there if you want.

**Comment by hugebdu** [comment]
@Hookyns confirm that in `https://github.com/Hookyns/ts-reflection/tree/feature/refactored-stores` works like magic.

Thanks!

**Comment by Hookyns** [comment]
I've published new versions of packages with fix:

`tst-reflect@0.6.0-beta.0`
`tst-reflect-transformer@0.9.0-beta.0`
