### ISSUE TITLE
Support of Enums

### ISSUE THREAD

**Issue by hugebdu** [Hookyns/ts-reflection#19]
Given something like 
```
  export interface Person {
    status: MaritalStatus;
  }

  enum MaritalStatus {
    Married = 0,
    Single = 1,
  }
```

Is there a way to get the enum name and literals while introspecting `Person` type property (`getType<Person>().getProperties()[0]`)?

I see that the property type kind is `Container` which totally makes sense, but cannot find neither the enum name nor its value names.

Thanks!

**Comment by Hookyns** [comment]
Hello,

kind `Container` is mainly for type operations such as Union and Intersection (Type1 | Type2 & Type3), it is not intended for enums, but yeah, it makes sense it fell to this kind.
I think I haven't test enums yet; I think the new `Enum` kind will be needed with new special handlers for that.

Now it generates
```javascript
___tst_reflect.Type.store.set(21838, {k: 6, n: "", v: 0});
___tst_reflect.Type.store.set(21839, {k: 6, n: "", v: 1});
___tst_reflect.Type.store.set(21837, {
	k: 3,
	types: [___tst_reflect.Type.store.get(21838), ___tst_reflect.Type.store.get(21839)],
	union: true,
	inter: false
});
```
Which is union of literals. There are values but no names,.. its under `Type.types`

What do you expect in Enum Type?
- name of the enum
- and enum itself? Or list of entries (`[ {property: "Single", value: 1}, { ... } ]`) or simple object (`{ "Married":0, "Single":1 }`)?

Enum is transpiled as:
```typescript
var SomeEnum;
(function (SomeEnum) {
    SomeEnum[SomeEnum["One"] = 0] = "One";
    SomeEnum[SomeEnum["Two"] = 1] = "Two";
})(SomeEnum || (SomeEnum = {}));
```
which gives you everything.. so reference to that enum should be enough.

**Comment by hugebdu** [comment]
indeed, reference to enum sounds good, but a discriminator is required to know it's an enum (maybe `TypeKind.Enum`?)

**Comment by Hookyns** [comment]
Okay, I've pushed implementation into same branch (`https://github.com/Hookyns/ts-reflection/tree/feature/refactored-stores`).

There is no reference to the real enum, it was quite problematic, because those enums can be in private modules (not exported) etc. and the enums would be useless without references. 

So I add
- `Enum` kind,
- `Type.isEnum(): boolean`,
- `Type.getEnum(): EnumInfo`

EnumInfo:
```typescript
interface EnumInfo
{
	/**
	 * Get enum enumerators/items (keys).
	 */
	getEnumerators(): string[];

	/**
	 * Get values.
	 */
	getValues(): any[];

	/**
	 * Get enum entries (key:value pairs).
	 */
	getEntries(): Array<readonly [enumeratorName: string, value: any]>;
}
```

**Comment by Hookyns** [comment]
I've published new versions of packages with implementation:

`tst-reflect@0.6.0-beta.0`
`tst-reflect-transformer@0.9.0-beta.0`

**Comment by hugebdu** [comment]
@Hookyns confirmed!
Thanks a lot!
Great lib, really like the idea, will see if I can use it for my use case (ORM schema definition via TS)

**Comment by Hookyns** [comment]
I thank you for this issue! 

Feel free to create another issues if you find something. 🙂

**Comment by hugebdu** [comment]
[just did](https://github.com/Hookyns/ts-reflection/issues/26) 😄
