### ISSUE TITLE
Metadata file and the Type::findType(): Type | undefined and Type::getTypes(): Array<Type> methods

### ISSUE THREAD

**Issue by Hookyns** [Hookyns/ts-reflection#2]
# Suggestion
Add optional behavior or change the default behavior which will generate metadata.js file which will contain all the information about types at one place. 

1. This should resolve the problem with circle dependencies,
2. no duplicit type declarations in generated .js files,
3. metadata can be used to find types eg. by name.

## Example
```typescript
const controllerType: Type = getType<Controller>();
const controllers = Type.getTypes().filter(type => type.isAssignableTo(controllerType));
```

---

Maybe something like @reflect() would be required to use on type declarations to optimize code. Or some configurations explicitly enabling metadata generation of all the types.

```typescript
@reflect
export default class HomeController {}
```

**Comment by Hookyns** [comment]
Metadata are generated into file from commit https://github.com/Hookyns/ts-reflection/commit/e8d6ff716590576979a1cad4adfb36250f12cff9

Methods findType and getTypes() soon.

**Comment by Hookyns** [comment]
New methods:
- `Type.find(): Type | undefined`
- `Type.getTypes(): Type[]`

```typescript
	/**
	 * Search the type store for a specific type
	 *
	 * Runs the provided filter callback on each type. If your filter returns true, it returns this type.
	 *
	 * @param {(type: Type) => boolean} filter
	 * @returns {Type | undefined}
	 */
	static find(filter: (type: Type) => boolean): Type | undefined;

	/**
	 * Returns all Types contained in metadata.
	 * This method is quite useless with reflection.metadata.type = "inline"; Use "typelib" type.
	 */
	static getTypes(): Type[];
```

**Comment by iDevelopThings** [comment]
Side note to anyone who looks at this too, this "find" method doesn't work if you use ts-node. I'm currently trying to find a fix for this
Maybe this should be documented somewhere 😅

**Comment by Hookyns** [comment]
> Side note to anyone who looks at this too, this "find" method doesn't work if you use ts-node. I'm currently trying to find a fix for this Maybe this should be documented somewhere 😅

It must work 😄 I'll try that.

**Comment by iDevelopThings** [comment]
> It must work 😄 I'll try that.

When using the meta lib file, it doesn't properly - atleast in this situation:  my main indexed file was index.ts, I had find in there. But with how ts-node compiles whilst it resolves require calls, the transformer doesn't run in time

> WTF,.. it doesn't work with ttsc either,.. find() nor getTypes(),.. Before 30 minutes I was using that,.. 😮

..... wait, it worked for me with ttsc O.o

**Comment by Hookyns** [comment]
```javascript
const ___tst_reflect = require("tst-reflect");
___tst_reflect.Type.store.set(21810, { k: 6, n: "One", v: 0 });
___tst_reflect.Type.store.set(21811, { k: 6, n: "Two", v: 1 });
___tst_reflect.Type.store.set(21809, { k: 13, n: "SomeEnum", types: [___tst_reflect.Type.store.get(21810), ___tst_reflect.Type.store.get(21811)] });
___tst_reflect.Type.store.set(21808, { k: 0, n: "Foo", fn: "@@this/dev/quick-tests/index.ts:Foo#21808", props: [{ n: "enum", t: ___tst_reflect.Type.store.get(21809), am: 2, acs: 0, ro: false, o: false }] });
var SomeEnum;
(function (SomeEnum) {
    SomeEnum[SomeEnum["One"] = 0] = "One";
    SomeEnum[SomeEnum["Two"] = 1] = "Two";
})(SomeEnum || (SomeEnum = {}));
const type = ___tst_reflect.Type.store.get(21808);
console.log(tst_reflect_1.Type.getTypes()); <--- tst_reflect_1 doesn't exist
```

**Comment by iDevelopThings** [comment]
https://github.com/Hookyns/ts-reflection/blob/c2c595716e65fbe23bd28f8568938e4b4ec7dd89/transformer/src/meta-writer/inline/InlineMetadataWriter.ts#L77

Maybe we remove this

It's technically fine to leave the import there i think 🤔

**Comment by Hookyns** [comment]
I've got it,..
It works in `metadata.type = typelib` mode, not in `inline`..

**Comment by Hookyns** [comment]
Now it works OK. `inline` and `typelib` too.
ts-node as well.. in `inline`... not in `typelib`

**Comment by iDevelopThings** [comment]
I'm so confused... it's now working fine for me O.o

**Comment by iDevelopThings** [comment]
Okay I think my main problem is just related to ts-node and the logic for this include/exclude system I'm working on. 

I think it's just a case of it not visiting the files defined, since i tapped some hacky logic onto the mainVisitor...

For this idea to work, it might have to be a program transformer O.o
