### ISSUE TITLE
imports from tst-reflect

### ISSUE THREAD

**Issue by hugebdu** [Hookyns/ts-reflection#26]
@Hookyns having some issues with the import, probably some bug in the transformer that messes up the import?
Assuming I need both `getType` and `TypeKind` imports, the only way it works for me is 
```
import { getType } from "tst-reflect";
import { TypeKind } from "tst-reflect";
```

Unifying into a single import (linters will note on that) like `import { getType, TypeKind } from "tst-reflect";` fails with 
```
tst_reflect_1 is not defined
ReferenceError: tst_reflect_1 is not defined
```

Tried also `import * as Reflect from "tst-reflect"` and then `Reflect.getType<MyInterface>()` - also no luck (in this case `getType` fails to reflect and returns an empty `Type`).

**Comment by hugebdu** [comment]
node 16, `ts-jest`, `ttypescript@1.5.13`, `typescript@4.5.4`

**Comment by Hookyns** [comment]
Do u have the latest versions of the tst-reflect and tst-reflect-transformer?

**Comment by hugebdu** [comment]
using `"tst-reflect-transformer": "0.9.0-beta.1"` and `"tst-reflect": "0.6.0-beta.4"`

**Comment by Hookyns** [comment]
I'll look at it in the evening. We have a little problem with circular modules in runtime package, so maybe this is related.

**Comment by hugebdu** [comment]
nothing urgent, it's your weekend I guess.
thanks!

**Comment by Hookyns** [comment]
@hugebdu Can u share some minimal example?

**Comment by hugebdu** [comment]
> Can u share some minimal example?

Ok, I think it's my fault, though I updated the `package.json` deps to the versions you published last time, my `tsconfig.json#compilerOptions#plugins#transform` was pointing to a local updated clone.
Changed to `tst-reflect-transformer` and have no issues with the imports.

Sorry for that.
IMHO can close.

Thanks!

**Comment by Hookyns** [comment]
Don't worry, no problem. :)
