### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iDevelopThings** [Hookyns/ts-reflection#9]
Hey, sorry I wanted to reach out, but couldn't find any contact info.

I was working on a similar package with some other useful features, then I discovered yours, I really like what you've put together here

Is there anything you're against adding to this reflection wise and would you be open to me submitting prs with some of the features I'd love? :) 

It doesn't make sense for me to release yet another package and such, it would make more sense for people with the same goal to work on a similar thing 😅

I was working on some reflection utilities but didn't get as far as you did, however I finished a system where interfaces have a type on runtime, which also have some reflection information - in a similar fashion to your "getType<Class/Interface>", it's possible to use "Interface<IService>" which the original declaration is replaced with an object and has some other things with it(still experimenting with the idea, but it allows for our interfaces to have a normal/available type on runtime, rather than vanishing from our code essentially) - I also did this for an IOC container implementation, similar to your goal here :D

If you'd like to discuss more, send me a dm on my twitter its on my profile... or we can discuss here, I don't mind

**Comment by Hookyns** [comment]
Move into the https://github.com/Hookyns/ts-reflection/discussions/10
